services:
  postgres_webgateway:
    container_name: postgres_catsservice
    image: postgres
    hostname: postgres_catsservice
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
volumes:
  postgres_data:
