spring.application.name=CatsService
spring.datasource.url=jdbc:postgresql://localhost:5435/postgres_catsservice
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.kafka.bootstrap-servers=localhost:9092
